Doesn't redirect stderr when getting verifier id
The logic fails when rally produces warnings [1].
It also updates Rally OpenStack and checks if the previous error
has been solved[2].

TypeError: _discover_or_create_flavor() missing 1 required positional
argument: 'flv_disk' [3]

[1] https://build.opnfv.org/ci/job/functest-opnfv-functest-healthcheck-latest-tempest_smoke-run/757/console
[2] https://github.com/openstack/rally-openstack/commit/e62315115af20e53f6c7205494ba0008634047ed
[3] https://build.opnfv.org/ci/job/functest-opnfv-functest-healthcheck-latest-tempest_smoke-run/629/console

Change-Id: Ia1daaa76d7cef7f30904c1f3bd42e2f6a6ba10af
Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
(cherry picked from commit 62f33836dfb2d24650ec7474d532e304d5d537f6)