Update Flake8
It avoids the next incompatibility:
ERROR: flake8 2.5.5 has requirement mccabe<0.5,>=0.2.1, but you'll have mccabe 0.6.1 which is incompatible.

Change-Id: Ic3bb14b032adfee64109549abc0a09d8cc86968f
Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
(cherry picked from commit 4d98d29002bf3ce61e1671db0b35c9046e2fbd8b)