Prevent from CloudifyClientError (key already exists)
It has rarely occured in Orange Openlab [1].

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/functest/core/cloudify.py", line 70, in execute
    self.cfy_client.secrets.create("foo", "bar")
  File "/usr/lib/python2.7/site-packages/cloudify_rest_client/secrets.py", line 86, in create
    response = self.api.put('/secrets/{0}'.format(key), data=data)
  File "/usr/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 263, in put
    timeout=timeout)
  File "/usr/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 224, in do_request
    verify=self.get_request_verify(), timeout=timeout)
  File "/usr/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 158, in _do_request
    self._raise_client_error(response, request_url)
  File "/usr/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 119, in _raise_client_error
    response=response)
  File "/usr/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 131, in _prepare_and_raise_exception
    status_code, error_code=error_code, response=response)
CloudifyClientError: 409: <Secret id=`foo` tenant=`default_tenant`> already exists on <Tenant name=`default_tenant`>

Change-Id: Ic61d0c729f13caa552a0b0a00dad35e50d130e01
Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
(cherry picked from commit b8a115906e4f6e598e7e1f1b59e2b1fb201af6a5)