Update patch set 5
Patch Set 5:

For snaps_smoke offline:
1) only one test about images failed: test_create_three_part_image_from_file_3_creators (snaps.openstack.tests.create_image_tests.CreateMultiPartImageTests)
The reason is that in def test_create_three_part_image_from_file_3_creators, although self.image_metadata is passed, only the key "kernel_file" is searched to get kernel_file_name, rather than "disk_file".
The detailed error log: http://paste.openstack.org/raw/613867/

2) test_apply_simple_playbook (snaps.provisioning.tests.ansible_utils_tests.AnsibleProvisioningTests)
   test_apply_template_playbook (snaps.provisioning.tests.ansible_utils_tests.AnsibleProvisioningTests)

The two tests also failed with some strange console log: http://paste.openstack.org/raw/613868/

FAIL: test_apply_simple_playbook (snaps.provisioning.tests.ansible_utils_tests.AnsibleProvisioningTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/snaps/provisioning/tests/ansible_utils_tests.py", line 200, in test_apply_simple_playbook
    self.assertTrue(self.inst_creator.vm_ssh_active(block=True))
AssertionError: False is not true

======================================================================
FAIL: test_apply_template_playbook (snaps.provisioning.tests.ansible_utils_tests.AnsibleProvisioningTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/snaps/provisioning/tests/ansible_utils_tests.py", line 253, in test_apply_template_playbook
    self.assertTrue(self.inst_creator.vm_ssh_active(block=True))
AssertionError: False is not true

Patch-set: 5