Remove lfreleng docs
Its output may has never been used and it's obsolete:
ERROR: lfdocs-conf 0.3.1 has requirement more-itertools~=5.0.0, but you'll have more-itertools 7.2.0 which is incompatible.
ERROR: lfdocs-conf 0.3.1 has requirement Sphinx~=1.8.5, but you'll have sphinx 2.2.0 which is incompatible.

Change-Id: Id5d24b94f6cdbbb93be8dbb18cde1a7fc9db6a42
Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
(cherry picked from commit 7ac977b6eaf9e3d3c79b47aa3fc36d291cb423b7)