Use ujson version asked by OpenStack master requirement
It's newer than the former tag selected [1].
The version asks by OpenStack train and older cannot work vs Alpine.

ImportError: Error relocating /usr/lib/python3.7/site-packages/ujson.cpython-37m-x86_64-linux-gnu.so: strreverse: symbol not found

[1] https://github.com/openstack/requirements/blob/master/upper-constraints.txt

Change-Id: Ie89136da364d7e972a1d7f49c71bdfbbdd9671d8
Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
(cherry picked from commit 743235f280b675cab39adb15de8bcea215a1c038)