Updated the robotframework-sshlibrary version
Currently, we have robotframework-sshlibrary version as 4.1.2 (which is non-existent) and while installing the libraries it will give the following:
ERROR: Could not find a version that satisfies the requirement robotframework-sshlibrary===4.1.2