Force a GET operations on cloudify API
Cloudify is considered as running by the client but sometimes it
failed when listing secrets right after. It adds that check in
cloudify.py.

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/functest/core/singlevm.py", line 391, in run
    if not self.execute():
  File "/usr/lib/python2.7/site-packages/functest/opnfv_tests/vnf/ims/cloudify_ims.py", line 119, in execute
    secrets_list = self.cfy_client.secrets.list()
  File "/usr/lib/python2.7/site-packages/cloudify_rest_client/secrets.py", line 113, in list
    response = self.api.get('/secrets', params=params)
  File "/usr/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 252, in get
    timeout=timeout)
  File "/usr/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 233, in do_request
    'SSL, but the client does'.format(e)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

Change-Id: Ie1b25ff529cfbf9f7476821499da369a46126e81
Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
(cherry picked from commit c4c3a33b9e6ae87c15331bf95e5544f0f680e4f0)