Update patch set 11
Patch Set 11:

> (2 comments)
 > 
 > The testcase seems linked to the testing env (eg PODs).
 > 
 > ERROR failed to bootstrap model: cannot start bootstrap instance:
 > cannot assign public address %!s(*string=0xc4204fdb60) to instance
 > "fcb9cb29-3b62-4920-99a8-91586c506649": failed to add floating ip
 > 172.31.18.100 to server with id: fcb9cb29-3b62-4920-99a8-91586c506649
 > caused by: request (http://172.31.18.51:8774/v2.1/180cc6975b184f4ea6dd0a2f00315607/servers/fcb9cb29-3b62-4920-99a8-91586c506649/action)
 > returned unexpected status: 400; error info: {"badRequest":
 > {"message": "Unable to associate floating IP 172.31.18.100 to fixed
 > IP 172.16.0.9 for instance fcb9cb29-3b62-4920-99a8-91586c506649.
 > Error: Bad floatingip request: Cannot process floating IP
 > association with Port 02dde4cb-4b94-4532-97fd-2e32a6489b4b, since
 > that port is owned by a different tenant.

Yes this is specific to cloud but it is being changed during runtime and taking auth_url value provided in openstack.creds . Also I can see from log that bootstrapped process is started but failed because instance was not getting floating IP . 
Although I am replacing the value mentioned abot_epc_cloud.yaml with a dummy value  in next patch .

Patch-set: 11
Reviewer: Gerrit User 6995 <6995@bbac25d2-bf60-4904-9ba8-a72fc000d6c5>
Label: Verified=0