Reduce Patrole test case lists
They seem related to Patrole obsolescence

patrole_tempest_plugin.rbac_exceptions.RbacParsingException: Attempted to test an invalid policy file or action
Details: Policy action "volume_extension:types_manage" not found in policy files: [] or among registered policy in code defaults for cinder service.

Change-Id: I2e0bfeb150c8835b47bddac7130021963850397a
Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
(cherry picked from commit c7a5cf97160a6b980249da846cd8c40430d42073)