Update patch set 1
Patch Set 1:

Flake8 Violations: 1
First 1 shown
---
 ./utils/functest_utils.py:21:1: F811 redefinition of unused 'subprocess' from line 20

Patch-set: 1
Label: Verified=-1