Check if key exists instead of leveraging on update_if_exists
It seems falsy (see line 72)

2019-01-07 11:50:32,550 - functest.core.cloudify - DEBUG - try 9: Cloudify Manager isn't up and running
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/functest/core/cloudify.py", line 72, in execute
    "foo", "bar", update_if_exists=True)
  File "/usr/lib/python2.7/site-packages/cloudify_rest_client/secrets.py", line 86, in create
    response = self.api.put('/secrets/{0}'.format(key), data=data)
  File "/usr/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 263, in put
    timeout=timeout)
  File "/usr/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 224, in do_request
    verify=self.get_request_verify(), timeout=timeout)
  File "/usr/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 158, in _do_request
    self._raise_client_error(response, request_url)
  File "/usr/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 119, in _raise_client_error
    response=response)
  File "/usr/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 131, in _prepare_and_raise_exception
    status_code, error_code=error_code, response=response)
CloudifyClientError: 409: <Secret id=`foo` tenant=`default_tenant`> already exists on <Tenant name=`default_tenant`>

Change-Id: I6f4e2719ad2e55e997ebbd158dce4c6a204b2c36
Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
(cherry picked from commit 0a0361f6a83b16c3c11f6077cda006cf7f15adf6)