Update patch set 1
Patch Set 1:

Flake8 Violations: 1
First 1 shown
---
 ./testcases/Controllers/ONOS/Teston/adapters/foundation.py:18:1: F811 redefinition of unused 're' from line 16

Patch-set: 1