Update patch set 1
Patch Set 1:

@Shuya, the unit tests are blocking the gate
py27 is FAIL due to 

GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --branch=master -v https://github.com/oolorg/opnfv-vnf-data.git /home/opnfv/functest/data/router/opnfv-vnf-data/
  stderr: 'Cloning into '/home/opnfv/functest/data/router/opnfv-vnf-data'...
fatal: unable to access 'https://github.com/oolorg/opnfv-vnf-data.git/': Failed to connect to github.com port 443: Connection refused


as the patch has been sumitted one week ago and there was no issue, and the page is properly answering from my browser, I assume there were some security changes

anyway unit tests must not be dependent to external repo. You can mock such things

Patch-set: 1