Update patch set 16
Patch Set 16:

> Sorry for the late review. I've been testing this patch on a Fuel
 > virtual environment (which could be the reason why it failed).
 > 
 > I got the following error:
 > 
 > 2017-07-05 11:13:01,418 - functest.opnfv_tests.vnf.ims.cloudify_ims
 > - INFO - Put private keypair in manager
 > 2017-07-05 11:13:31,449 - functest.core.vnf - ERROR - Exception on
 > VNF testing
 > Traceback (most recent call last):
 > File "/usr/local/lib/python2.7/dist-packages/functest/core/vnf.py",
 > line 70, in run
 > if (self.deploy_orchestrator() and
 > File "/usr/local/lib/python2.7/dist-packages/functest/opnfv_tests/vnf/ims/cloudify_ims.py",
 > line 263, in deploy_orchestrator
 > scp.put(kp_file, '~/')
 > File "/usr/local/lib/python2.7/dist-packages/scp.py", line 146, in
 > put
 > self._recv_confirm()
 > File "/usr/local/lib/python2.7/dist-packages/scp.py", line 316, in
 > _recv_confirm
 > raise SCPException('Timout waiting for scp response')
 > SCPException: Timout waiting for scp response

we already faced some issues on virtual environment (timeout) in previous versions
here as we precised the scenario os-nosdn-nofeature-ha, it excludes all the noha scenarios that usually run on virtual env
but it does not prevent runs on virtual ha.... 
what was your fuel scenario?

for the moment the risk is limited because some blocking tests will fail before...we may increase the timeout..the test case deploy several VMs which may take some time

Patch-set: 16