Update patch set 4
Patch Set 4: Code-Review-1

The prerequisite for this patch is, run_tests.py should be the only entry point for Functest. However, this assumption is not true for the existing situation. This is the main reason why functest_logger is kept during my last change to logger stuff.

Take prepare_env.py for example, 'no handler for logger' popped in this patch
---------------------------
root@cd5e0e7f1a31:~/repos/functest# python functest/ci/prepare_env.py start
2017-05-03 01:11:42,150 - opnfv.deployment.compass.adapter - ERROR - No nodes are found in the deployment.
fetch_os_creds.info: Verifying connectivity to 192.168.200.2...
fetch_os_creds.info: 192.168.200.2 is reachable!
fetch_os_creds.error: The controller  is not up. Please check that the POD is correctly deployed.
No handlers could be found for logger "__main__"
root@cd5e0e7f1a31:~/repos/functest# functest env prepare
2017-05-03 01:12:23,160 - opnfv.deployment.compass.adapter - ERROR - No nodes are found in the deployment.
No handlers could be found for logger "__main__"
No handlers could be found for logger "functest.utils.functest_utils"
-----------------------------

Also, logging.ini is an old style which is not easy to interpret. I would stick to logging.json.

Patch-set: 4
Label: Code-Review=-1