Pin rally-openstack in master
The last patch seems buggy [1]
TypeError: _discover_or_create_flavor() missing 1 required positional argument: 'flv_disk' [2]

[1] https://github.com/openstack/rally-openstack/commit/e62315115af20e53f6c7205494ba0008634047ed
[2] https://build.opnfv.org/ci/job/functest-opnfv-functest-healthcheck-latest-tempest_smoke-run/629/console

Change-Id: Id0402afdf79d7a1081e817ea513d90c93b077ce4
Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>