Update patch set 2
Patch Set 2:

Flake8 Violations: 1
First 1 shown
---
 ./utils/functest_utils.py:21:1: F811 redefinition of unused 'subprocess' from line 20

Patch-set: 2
Label: Verified=-1