Update patch set 3
Patch Set 3:

> The following error was not observed in my development environment
 > and may be some sort of namespace issue in the PYTHONPATH. I may
 > need some help with this one:
 > 
 > IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/examples/heat/test_heat_template.yaml'

This error is missing when I tested it today.

Patch-set: 3