Skip manage_snapshot in CNTT
As detected by Orange's RC Field trial, Ceph doesn't support this
feature before Rocky [1].
"AttributeError: 'RBDDriver' object has no attribute 'unmanage_snapshot'"

manage_snapshot testing is fully passing in Functest SUT because CNTT
is verified vs OpenStack Rocky and newer.

Ceph is selected by RI as backend and is widely reused by the ecosytem.
It's similar to [2].

[1] https://bugs.launchpad.net/cinder/+bug/1645288
[2] https://gerrit.opnfv.org/gerrit/c/functest/+/69888

Change-Id: I3b7f88f5bed9a47a1e26e16bbbf74fea24ca76c2
Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
(cherry picked from commit 830d508837f3b1011eeb44c3d5af5961fbf4c701)